version: '3.8'

services:
  sender:
    image: sender:latest
    container_name: sender
    build:
      context: .
      dockerfile: Sender/Dockerfile.sender
    ports:
      - "5000:5000"
      - "6000:6000"
      - "8000:8000"  # GUI port
    volumes:
      - ./Sender/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.11

  receiver:
    image: receiver:latest
    container_name: receiver
    build:
      context: .
      dockerfile: ./Receiver/Dockerfile.receiver
    ports:
      - "5001:5001"
      - "5050:5050"
      - "8001:8001"  # GUI port
    volumes:
      - ./Receiver/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.12

  krc:
    image: krc:latest
    container_name: krc
    build:
      context: .
      dockerfile: KRC/Dockerfile.KRC
    ports:
      - "5002:5002"
      - "8002:8002"  # GUI port
    volumes:
      - ./KRC/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.13

  kra-1:
    image: kra:latest
    container_name: kra-1
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    environment:
      KRA_ID: kra1
      LISTEN_PORT: 5003
      GUI_PORT: 8003
    ports:
      - "5003:5003"
      - "8003:8003"  # GUI port
    volumes:
      - ./KRA/kra1/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.14

  kra-2:
    image: kra:latest
    container_name: kra-2
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    environment:
      KRA_ID: kra2
      LISTEN_PORT: 5004
      GUI_PORT: 8004
    ports:
      - "5004:5004"
      - "8004:8004"
    volumes:
      - ./KRA/kra2/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.15

  kra-3:
    image: kra:latest
    container_name: kra-3
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    environment:
      KRA_ID: kra3
      LISTEN_PORT: 5005
      GUI_PORT: 8005
    ports:
      - "5005:5005"
      - "8005:8005"
    volumes:
      - ./KRA/kra3/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.16

  kra-4:
    image: kra:latest
    container_name: kra-4
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    environment:
      KRA_ID: kra4
      LISTEN_PORT: 5006
      GUI_PORT: 8006
    ports:
      - "5006:5006"
      - "8006:8006"
    volumes:
      - ./KRA/kra4/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.17

  kra-5:
    image: kra:latest
    container_name: kra-5
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    environment:
      KRA_ID: kra5
      LISTEN_PORT: 5007
      GUI_PORT: 8007
    ports:
      - "5007:5007"
      - "8007:8007"
    volumes:
      - ./KRA/kra5/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
    networks:
      app_network:
        ipv4_address: 192.168.1.18

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24