version: '3.8'

services:
  genkeys:
    build:
      context: ./generate_key
      dockerfile: Dockerfile.genkey
    volumes:
      - ./Shared/keys:/Shared/keys
      - ./Sender/keys:/Sender/keys
      - ./Receiver/keys:/Receiver/keys
      - ./KRC/keys:/KRC/keys
      - ./KRA/kra1/keys:/KRA/kra1/keys
      - ./KRA/kra2/keys:/KRA/kra2/keys
      - ./KRA/kra3/keys:/KRA/kra3/keys
      - ./KRA/kra4/keys:/KRA/kra4/keys
      - ./KRA/kra5/keys:/KRA/kra5/keys
    command: ["python", "GenKey.py"]

  sender:
    build:
      context: ./Sender
      dockerfile: Dockerfile.sender
    depends_on:
      - genkeys
    ports:
      - "5000:5000"
    volumes:
      - ./Sender/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  receiver:
    build:
      context: ./Receiver
      dockerfile: Dockerfile.receiver
    depends_on:
      - genkeys
    ports:
      - "5001:5001"
    volumes:
      - ./Receiver/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  krc:
    build:
      context: ./KRC
      dockerfile: Dockerfile.KRC
    depends_on:
      - genkeys
    ports:
      - "5002:5002"
    volumes:
      - ./KRC/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  kra1:
    build:
      context: ./KRA/kra1
      dockerfile: Dockerfile.KRA
    depends_on:
      - genkeys
    ports:
      - "5003:5003"
    volumes:
      - ./KRA/kra1/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  kra2:
    build:
      context: ./KRA/kra2
      dockerfile: Dockerfile.KRA
    depends_on:
      - genkeys
    ports:
      - "5004:5004"
    volumes:
      - ./KRA/kra2/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  kra3:
    build:
      context: ./KRA/kra3
      dockerfile: Dockerfile.KRA
    depends_on:
      - genkeys
    ports:
      - "5005:5005"
    volumes:
      - ./KRA/kra3/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  kra4:
    build:
      context: ./KRA/kra4
      dockerfile: Dockerfile.KRA
    depends_on:
      - genkeys
    ports:
      - "5006:5006"
    volumes:
      - ./KRA/kra4/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys

  kra5:
    build:
      context: ./KRA/kra5
      dockerfile: Dockerfile.KRA
    depends_on:
      - genkeys
    ports:
      - "5007:5007"
    volumes:
      - ./KRA/kra5/keys:/app/keys
      - ./Shared/keys:/app/Shared/keys
