version: "3.8"
services:
  sender:
    container_name: Sender
    build:
      context: ./Sender
      dockerfile: Dockerfile.sender
    networks:
      sfm_krs_network:
        ipv4_address: 192.168.1.2

  receiver:
    container_name: Receiver
    build:
      context: ./Receiver
      dockerfile: Dockerfile.receiver
    networks:
      sfm_krs_network:
        ipv4_address: 192.168.1.3

  krc:
    container_name: KRC
    build:
      context: ./KRC
      dockerfile: Dockerfile.KRC
    networks:
      sfm_krs_network:
        ipv4_address: 192.168.1.4
        
  kra:
    container_name: KRA
    build:
      context: ./KRA
      dockerfile: Dockerfile.KRA
    networks:
      sfm_krs_network:
        ipv4_address: 192.168.1.5

networks:
  sfm_krs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24