version: '3.8'
services:
  server:
    build:
      context: .
    container_name: server
    networks:
      - my_network
    ports:
      - "5000:5000"
    command: python server.py

  client:
    build:
      context: .
    container_name: client
    networks:
      - my_network
    depends_on:
      - server
    environment:
      - MESSAGE=Hello from Client!
    command: python client.py

networks:
  my_network:
    external: true