FROM python:3.9-slim

# ตั้งค่า Working Directory
WORKDIR /app

# คัดลอกไฟล์ Script และ Key ที่เกี่ยวข้อง
COPY krc_script.py ./
COPY keys/krc_private_key.pem ./keys/
COPY keys/krc_public_key.pem ./keys/

# ติดตั้ง dependency ที่จำเป็น
RUN pip install cryptography

# คำสั่งเริ่มต้นการรัน Script
CMD ["python", "krc_script.py"]
