FROM python:3.9-slim
WORKDIR /app
COPY receiver_script.py ./
COPY keys/receiver_private_key.pem ./keys/
COPY keys/receiver_public_key.pem ./keys/
RUN pip install cryptography
CMD ["python", "receiver_script.py"]
