FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y iputils-ping
RUN apt install curl -y

# Install Python dependencies
RUN pip install flask
RUN pip install requests

# Copy application code to the container
WORKDIR /app
COPY ./app.py /app
COPY ./data.json .
COPY ./send_json.py .


# Expose port and run app
EXPOSE 5000
CMD ["python", "app.py"]