FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y iputils-ping

# Install Python dependencies
RUN pip install flask

# Copy application code to the container
WORKDIR /app
COPY ./app.py /app

# Expose port and run app
EXPOSE 5000
CMD ["python", "app.py"]